name: Deploy AIOps Lambdas to AWS

on:
  # This makes the workflow run on pushes to the 'main' branch
  push:
    branches:
    - main
    paths:
    - 'src/lambda_functions/**'

  # This allows you to run the workflow manually from the Actions tab
  workflow_dispatch:


jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1 # IMPORTANT: Make sure this matches your Terraform region

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Install Zip
      run: sudo apt-get install -y zip

    - name: Build and Deploy Lambdas
      run: |
        # Navigate into the functions directory
        cd src/lambda_functions

        # Loop through each individual lambda function directory
        for lambda_dir in */ ; do
          # Clean up the name
          LAMBDA_NAME=${lambda_dir%/}
          echo "--------------------------------------------------"
          echo "Processing Lambda function: $LAMBDA_NAME"
          echo "--------------------------------------------------"

          # Create a temporary directory for packaging
          mkdir -p package

          # Install dependencies into the package directory if requirements.txt exists
          if [ -f "$LAMBDA_NAME/requirements.txt" ]; then
            pip install -r "$LAMBDA_NAME/requirements.txt" -t "package/"
          fi

          # Copy the function's own code into the package directory
          cp "$LAMBDA_NAME/app.py" "package/"

          # Create the zip file from the contents of the package directory
          (cd package && zip -r ../${LAMBDA_NAME}.zip .)

          # Deploy the zip file to AWS Lambda
          aws lambda update-function-code \
            --function-name aiops-self-healing-${LAMBDA_NAME//_/-} \
            --zip-file fileb://${LAMBDA_NAME}.zip
          
          # Clean up the temporary directories and zip file
          rm -rf package
          rm ${LAMBDA_NAME}.zip
        done
